name: CI API Tests
on:
  pull_request:
    types: ['opened']
    branches:
      - 'my_branch'
jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependecies
      run: npm ci
    - name: Run api test
      run: npm run api_tests
